<?php

$_code = $this->getMethodCode();
$billingInformation = $this->getCurrentBillingInformation();
$availableCoinsJson = json_encode($this->getListAvailableCoins());
$total = $this->getGrandTotal();

?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
<!--    <li>-->
<!--        <label for="--><?php //echo $_code ?><!--_buyer_email" class="required"><em>*</em>--><?php //echo $this->__('Buyer Email') ?>
<!--        </label>-->
<!--        <div class="input-box">-->
<!--            <input type="text" id="--><?php //echo $_code ?><!--_buyer_email" name="payment[_buyer_email]"-->
<!--                   title="--><?php //echo $this->__('Buyer Email') ?><!--" class="input-text"-->
<!--                   value="--><?php //echo $billingInformation['email'] ?><!--"/>-->
<!--        </div>-->
<!--    </li>-->
    <li>
        <label for="<?php echo $_code ?>_currency2" class="required"><em>*</em><?php echo $this->__('Currency') ?>
        </label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_currency2" name="payment[_currency2]"
                    class="required-entry validate-currency2-select"
                    data-available-coins='<?php echo $availableCoinsJson ?>'
                    data-order-total="<?php echo $total ?>"
                    data-element-to-change="<?php echo $_code; ?>_currency_amount"
                    onchange="amountToCurrency(this)"
            >
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php foreach ($this->getListAvailableCoins() as $type => $currency): ?>
                    <option value="<?php echo $type ?>"><?php echo $currency->name . ' (' . $type . ')' ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_currency_amount"><em>*</em><?php echo $this->__('Currency Amount') ?>
        </label>
        <div class="input-box">
            <span id="<?php echo $_code ?>_currency_amount"><?php echo $total; ?><span>
        </div>
    </li>
</ul>
